language: python
sudo: false
python:
  - 3.4.3
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -e .[dev]

script:
  - py.test codetransformer
  - flake8 codetransformer

notifications:
  email: false
